package it.epicode.BE_W7_D3.esercizio2;

import com.github.javafaker.Faker;
import it.epicode.BE_W7_D3.faker.FakerConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
@Order(2)
public class LibroRunner implements CommandLineRunner {
    @Autowired
    Faker faker;
    @Override
    public void run(String... args) throws Exception {
        System.out.println("ESERCIZIO 2:");
        Pagina pagina1 = new Pagina("Pagina 1");
        Pagina pagina2 = new Pagina("Pagina 2");
        Pagina pagina3 = new Pagina("Pagina 3");
        Pagina pagina4 = new Pagina("Pagina 4");
        Pagina pagina5 = new Pagina("Pagina 5");
        Pagina pagina6 = new Pagina("Pagina 6");
        Pagina pagina7 = new Pagina("Pagina 7");
        Pagina pagina8 = new Pagina("Pagina 8");
        Pagina pagina9 = new Pagina("Pagina 9");
        Pagina pagina10 = new Pagina("Pagina 10");
        Pagina pagina11 = new Pagina("Pagina 11");
        Pagina pagina12 = new Pagina("Pagina 12");
        Pagina pagina13 = new Pagina("Pagina 13");
        Pagina pagina14 = new Pagina("Pagina 14");
        Pagina pagina15 = new Pagina("Pagina 15");
        Pagina pagina16 = new Pagina("Pagina 16");
        Pagina pagina17 = new Pagina("Pagina 17");
        Pagina pagina18 = new Pagina("Pagina 18");
        Pagina pagina19 = new Pagina("Pagina 19");
        Pagina pagina20 = new Pagina("Pagina 20");
        Pagina pagina21 = new Pagina("Pagina 21");
        Pagina pagina22 = new Pagina("Pagina 22");
        Pagina pagina23 = new Pagina("Pagina 23");
        Pagina pagina24 = new Pagina("Pagina 24");
        Pagina pagina25 = new Pagina("Pagina 25");
        Pagina pagina26 = new Pagina("Pagina 26");
        Pagina pagina27 = new Pagina("Pagina 27");
        Pagina pagina28 = new Pagina("Pagina 28");
        Pagina pagina29 = new Pagina("Pagina 29");
        Pagina pagina30 = new Pagina("Pagina 30");
        Pagina pagina31 = new Pagina("Pagina 31");
        Pagina pagina32 = new Pagina("Pagina 32");
        Pagina pagina33 = new Pagina("Pagina 33");
        Pagina pagina34 = new Pagina("Pagina 34");
        Pagina pagina35 = new Pagina("Pagina 35");
        Pagina pagina36 = new Pagina("Pagina 36");
        Pagina pagina37 = new Pagina("Pagina 37");
        Pagina pagina38 = new Pagina("Pagina 38");
        Pagina pagina39 = new Pagina("Pagina 39");
        Pagina pagina40 = new Pagina("Pagina 40");
        Pagina pagina41 = new Pagina("Pagina 41");
        Pagina pagina42 = new Pagina("Pagina 42");
        Pagina pagina43 = new Pagina("Pagina 43");
        Pagina pagina44 = new Pagina("Pagina 44");
        Pagina pagina45 = new Pagina("Pagina 45");
        Pagina pagina46 = new Pagina("Pagina 46");
        Pagina pagina47 = new Pagina("Pagina 47");
        Pagina pagina48 = new Pagina("Pagina 48");
        Pagina pagina49 = new Pagina("Pagina 49");
        Pagina pagina50 = new Pagina("Pagina 50");
        Pagina pagina51 = new Pagina("Pagina 51");
        Pagina pagina52 = new Pagina("Pagina 52");
        Pagina pagina53 = new Pagina("Pagina 53");
        Pagina pagina54 = new Pagina("Pagina 54");
        Pagina pagina55 = new Pagina("Pagina 55");
        Pagina pagina56 = new Pagina("Pagina 56");
        Pagina pagina57 = new Pagina("Pagina 57");
        Pagina pagina58 = new Pagina("Pagina 58");
        Pagina pagina59 = new Pagina("Pagina 59");
        Pagina pagina60 = new Pagina("Pagina 60");
        Pagina pagina61 = new Pagina("Pagina 61");
        Pagina pagina62 = new Pagina("Pagina 62");
        Pagina pagina63 = new Pagina("Pagina 63");
        Pagina pagina64 = new Pagina("Pagina 64");
        Pagina pagina65 = new Pagina("Pagina 65");
        Pagina pagina66 = new Pagina("Pagina 66");
        Pagina pagina67 = new Pagina("Pagina 67");
        Pagina pagina68 = new Pagina("Pagina 68");
        Pagina pagina69 = new Pagina("Pagina 69");
        Pagina pagina70 = new Pagina("Pagina 70");
        Pagina pagina71 = new Pagina("Pagina 71");
        Pagina pagina72 = new Pagina("Pagina 72");
        Pagina pagina73 = new Pagina("Pagina 73");
        Pagina pagina74 = new Pagina("Pagina 74");
        Pagina pagina75 = new Pagina("Pagina 75");
        Pagina pagina76 = new Pagina("Pagina 76");
        Pagina pagina77 = new Pagina("Pagina 77");
        Pagina pagina78 = new Pagina("Pagina 78");
        Pagina pagina79 = new Pagina("Pagina 79");
        Pagina pagina80 = new Pagina("Pagina 80");
        Pagina pagina81 = new Pagina("Pagina 81");
        Pagina pagina82 = new Pagina("Pagina 82");
        Pagina pagina83 = new Pagina("Pagina 83");
        Pagina pagina84 = new Pagina("Pagina 84");
        Pagina pagina85 = new Pagina("Pagina 85");
        Pagina pagina86 = new Pagina("Pagina 86");
        Pagina pagina87 = new Pagina("Pagina 87");
        Pagina pagina88 = new Pagina("Pagina 88");
        Pagina pagina89 = new Pagina("Pagina 89");
        Pagina pagina90 = new Pagina("Pagina 90");
        Pagina pagina91 = new Pagina("Pagina 91");
        Pagina pagina92 = new Pagina("Pagina 92");
        Pagina pagina93 = new Pagina("Pagina 93");
        Pagina pagina94 = new Pagina("Pagina 94");
        Pagina pagina95 = new Pagina("Pagina 95");
        Pagina pagina96 = new Pagina("Pagina 96");
        Pagina pagina97 = new Pagina("Pagina 97");
        Pagina pagina98 = new Pagina("Pagina 98");
        Pagina pagina99 = new Pagina("Pagina 99");
        Pagina pagina100 = new Pagina("Pagina 100");

        List<Pagina> pagineSezione1 = List.of(pagina1, pagina2, pagina3, pagina4, pagina5, pagina6, pagina7, pagina8, pagina9, pagina10);
        List<Pagina> pagineSezione2 = List.of(pagina11, pagina12, pagina13, pagina14, pagina15, pagina16, pagina17, pagina18, pagina19, pagina20);
        List<Pagina> pagineSezione3 = List.of(pagina21, pagina22, pagina23, pagina24, pagina25, pagina26, pagina27, pagina28, pagina29, pagina30);
        List<Pagina> pagineSezione4 = List.of(pagina31, pagina32, pagina33, pagina34, pagina35, pagina36, pagina37, pagina38, pagina39, pagina40);
        List<Pagina> pagineSezione5 = List.of(pagina41, pagina42, pagina43, pagina44, pagina45, pagina46, pagina47, pagina48, pagina49, pagina50);
        List<Pagina> pagineSezione6 = List.of(pagina51, pagina52, pagina53, pagina54, pagina55, pagina56, pagina57, pagina58, pagina59, pagina60);
        List<Pagina> pagineSezione7 = List.of(pagina61, pagina62, pagina63, pagina64, pagina65, pagina66, pagina67, pagina68, pagina69, pagina70);
        List<Pagina> pagineSezione8 = List.of(pagina71, pagina72, pagina73, pagina74, pagina75, pagina76, pagina77, pagina78, pagina79, pagina80);
        List<Pagina> pagineSezione9 = List.of(pagina81, pagina82, pagina83, pagina84, pagina85, pagina86, pagina87, pagina88, pagina89, pagina90);
        List<Pagina> pagineSezione10 = List.of(pagina91, pagina92, pagina93, pagina94, pagina95, pagina96, pagina97, pagina98, pagina99, pagina100);

        Sezione sezione1 = new Sezione();
        sezione1.setPagine(pagineSezione1);
        sezione1.setTitolo("Sezione 1");
        Sezione sezione2 = new Sezione();
        sezione2.setPagine(pagineSezione2);
        sezione2.setTitolo("Sezione 2");
        Sezione sezione3 = new Sezione();
        sezione3.setPagine(pagineSezione3);
        sezione3.setTitolo("Sezione 3");
        Sezione sezione4 = new Sezione();
        sezione4.setTitolo("Sezione 4");
        sezione4.setPagine(pagineSezione4);
        Sezione sezione5 = new Sezione();
        sezione5.setTitolo("Sezione 5");
        sezione5.setPagine(pagineSezione5);
        Sezione sezione6 = new Sezione();
        sezione6.setTitolo("Sezione 6");
        sezione6.setPagine(pagineSezione6);
        sezione6.setSottoSezioni(List.of(sezione1, sezione2));
        Sezione sezione7 = new Sezione();
        sezione7.setTitolo("Sezione 7");
        sezione7.setPagine(pagineSezione7);
        sezione7.setSottoSezioni(List.of(sezione3));
        Sezione sezione8 = new Sezione();
        sezione8.setTitolo("Sezione 8");
        sezione8.setPagine(pagineSezione8);
        sezione8.setSottoSezioni(List.of(sezione4, sezione5, sezione6, sezione7));
        Sezione sezione9 = new Sezione();
        sezione9.setTitolo("Sezione 9");
        sezione9.setPagine(pagineSezione9);
        sezione9.setSottoSezioni(List.of(sezione2,sezione4));
        Sezione sezione10 = new Sezione();
        sezione10.setPagine(pagineSezione10);
        sezione10.setTitolo("Sezione 10");
        sezione10.setSottoSezioni(List.of(sezione8));

        Autore autore1 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore2 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore3 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore4 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore5 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore6 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore7 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore8 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore9 = new Autore(faker.name().firstName(), faker.name().lastName());
        Autore autore10 = new Autore(faker.name().firstName(), faker.name().lastName());

        Libro libro1 = new Libro();
        libro1.setAutore(List.of(autore1, autore2));
        libro1.setTitolo(faker.book().title());
        libro1.setPrezzo(faker.number().randomDouble(2, 5, 30));
        libro1.setSezioni(List.of(sezione1, sezione7, sezione8, sezione9, sezione10));
        System.out.println(libro1);
        System.out.println(libro1.getNumeroPagine());
        System.out.println("-----------------------------------");
    }


}
